### ISSUE TITLE
[bug] Cannot set property 'screen' of undefined

### ISSUE THREAD

**Issue by Goopil** [quasarframework/quasar-nuxt#2] opened 2018-06-22 05:29 UTC
### Software version
quasar-nuxt: ^0.16.0-alpha.2
OS: win 10
Node: v8.11.3
NPM: 6
Browsers: chrome

Any other software related to your bug:
nuxt: 1.4

### What did you get as the error?

Nuxt fresh Install with quasar-nuxt package

### What steps did you take, to get the error?
just a fresh install with your in dev plugin then `npm run dev`

### error received

Cannot set property 'screen' of undefined

```js

// node_modules/quasar-framework/dist/quasar.mat.esm.js:19633
 install: function install (ref) {
    var this$1 = this;
    var $q = ref.$q;
    var Vue = ref.Vue;

    if (this.__installed) { return }
    this.__installed = true;

    if (isSSR) {
      this.$q.screen = this; // $q is undefined in the esm build
      this.setSizes = this.setDebounce = function () {};
      return
    }
...
}
```

**Comment by rstoenescu** [comment] 2018-06-22 09:15
Duplicate of https://github.com/quasarframework/quasar-nuxt/issues/1

This does not works with the current released Quasar version. Next version is SSR compatible, so please wait for it. Thanks.

**Closed as completed by rstoenescu** 2018-06-22 09:15 UTC

**Comment by Goopil** [comment] 2018-06-22 11:44
Sorry didn't see the #1 thanks for letting me know
